#!/usr/bin/env python3
"""Generate compact LaTeX tabular fragments from key SI CSVs.

"""
from __future__ import annotations
from pathlib import Path
import pandas as pd
import numpy as np


PKG = Path(__file__).resolve().parent.parent
TABLES_CSV = PKG / "tables"
TABLES_TEX = PKG / "manuscript" / "tables_tex"
TABLES_TEX.mkdir(parents=True, exist_ok=True)


def _fmt(x, prec=3):
    """LaTeX-safe scalar formatter."""
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "---"
    if isinstance(x, (int, np.integer)):
        return f"{x:,}"
    if isinstance(x, float):
        if x == 0:
            return "0"
        ax = abs(x)
        if ax < 1e-3 or ax >= 1e4:
            return f"${x:.{prec - 1}e}$".replace("e", r" \times 10^{") + "}$"
        return f"{x:.{prec}g}"
    s = str(x).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")
    return s


def write_table(name, caption, label, header, rows, colspec=None, fontsize=r"\small"):
    """Emit a `\begin{table}` block with `tabular` body."""
    if colspec is None:
        colspec = "l" + "r" * (len(header) - 1)
    head_tex = " & ".join(header) + r" \\"
    body = "\n".join(" & ".join(r) + r" \\" for r in rows)
    tex = (
        f"% Auto-generated by build_si_tables.py — do not edit.\n"
        f"\\begin{{table}}[ht]\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        f"\\centering\n"
        f"{fontsize}\n"
        f"\\begin{{tabular}}{{{colspec}}}\n"
        f"\\toprule\n"
        f"{head_tex}\n"
        f"\\midrule\n"
        f"{body}\n"
        f"\\bottomrule\n"
        f"\\end{{tabular}}\n"
        f"\\end{{table}}\n"
    )
    out = TABLES_TEX / f"{name}.tex"
    out.write_text(tex)
    print(f"  wrote {out.relative_to(PKG)} ({len(rows)} rows)")


def t_centroid_ridge():
    df = pd.read_csv(TABLES_CSV / "centroid_ridge_main.csv")
    cols = [
        "Contrast",
        "log10Da_centroid_f095",
        "log10Da_centroid_f095_lo",
        "log10Da_centroid_f095_hi",
        "HI_peak_curve",
        "width_decades_f095",
    ]
    df = df[cols].copy()
    rows = []
    for _, r in df.iterrows():
        rows.append([
            f"{r['Contrast']:.2f}",
            f"{r['log10Da_centroid_f095']:.3f}",
            f"[{r['log10Da_centroid_f095_lo']:.3f}, {r['log10Da_centroid_f095_hi']:.3f}]",
            f"{r['HI_peak_curve']:.3f}",
            f"{r['width_decades_f095']:.2f}",
        ])
    write_table(
        "centroid_ridge_main",
        caption=(
            "Per-contrast ridge centroid location ($\\log_{10}\\mathrm{Da}_{\\mathrm{centroid}}$ "
            "with bootstrap 16th--84th percentile interval), peak HI value at the centroid, "
            "and ridge width measured at the 95\\textsuperscript{th}-percentile-of-peak "
            "threshold ($f_{095}$)."
        ),
        label="tab:centroid_ridge_main",
        header=["$R$", "$\\log_{10}\\mathrm{Da}_c$", "68\\% CI", "$\\mathrm{HI}_{\\mathrm{peak}}$", "Width (dec.)"],
        rows=rows,
        colspec="rrcrr",
        fontsize=r"\footnotesize",
    )


def _sci(x, prec=2):
    """Format x as $a \\times 10^{b}$ for LaTeX."""
    if x == 0 or not np.isfinite(x):
        return "0"
    exp = int(np.floor(np.log10(abs(x))))
    mant = x / (10 ** exp)
    return f"${mant:.{prec}f}\\times 10^{{{exp}}}$"


def _display_id(sid: str) -> str:
    """Format a system_id for display in SI tables.

    USGS gauge IDs are canonically 8 digits; some of our internal CSV
    fields store them without the leading zero (e.g., "1013500" for Fish
    River near Fort Kent, ME). For display we strip the "USGS-" prefix
    and zero-pad pure-numeric IDs to 8 digits so the shown identifier
    matches USGS NWIS and the main text.
    """
    s = str(sid).replace("USGS-", "")
    if s.isdigit():
        s = s.zfill(8)
    return s.replace("_", r"\_")


def t_dt_convergence():
    df = pd.read_csv(TABLES_CSV / "dt_convergence.csv")
    grp = df.groupby(["zone", "N_T"])["abs_error"].agg(["median", "max", "count"]).reset_index()
    rows = []
    for _, r in grp.iterrows():
        rows.append([
            str(r["zone"]).replace("_", r"\_"),
            f"{int(r['N_T'])}",
            f"{int(r['count'])}",
            _sci(r["median"]),
            _sci(r["max"]),
        ])
    write_table(
        "dt_convergence",
        caption=(
            "Timestep convergence of the primary RK4 integrator versus the "
            "Radau IVP reference ($\\mathrm{rtol} = 10^{-10}$). Median and "
            "maximum $|\\Delta\\mathrm{HI}|$ are reported by zone and timestep "
            "count $N_T$ across representative realizations."
        ),
        label="tab:dt_convergence",
        header=["Zone", "$N_T$", "$n$", "Median $|\\Delta\\mathrm{HI}|$", "Max $|\\Delta\\mathrm{HI}|$"],
        rows=rows,
        colspec="lrrrr",
    )


def t_forcing_stress_summary():
    df = pd.read_csv(TABLES_CSV / "forcing_stress_sensitivity.csv")
    df = df[df["scenario_id"].notna()].copy()
    grp = df.groupby("scenario_id").agg(
        n_pairs=("dlog10Da_centroid_f095_vs_baseline", "size"),
        max_abs_shift=("dlog10Da_centroid_f095_vs_baseline", lambda s: s.abs().max()),
        median_abs_shift=("dlog10Da_centroid_f095_vs_baseline", lambda s: s.abs().median()),
    )
    grp["n_exceed_0p3"] = df.groupby("scenario_id")["dlog10Da_centroid_f095_vs_baseline"].apply(
        lambda s: (s.abs() > 0.3).sum()
    )
    grp = grp.reset_index().sort_values("max_abs_shift", ascending=False)
    rows = []
    for _, r in grp.iterrows():
        rows.append([
            str(r["scenario_id"]).replace("_", r"\_"),
            f"{int(r['n_pairs'])}",
            f"{r['max_abs_shift']:.2f}",
            f"{r['median_abs_shift']:.2f}",
            f"{int(r['n_exceed_0p3'])}",
        ])
    write_table(
        "forcing_stress_summary",
        caption=(
            "Forcing-perturbation summary by scenario: number of "
            "(scenario,~contrast) pairs, maximum and median absolute centroid "
            "shift in decades of $\\log_{10}\\mathrm{Da}$ versus the baseline pulse, "
            "and the count of pairs whose absolute shift exceeds the 0.3-decade "
            "stable-ridge tolerance."
        ),
        label="tab:forcing_stress_summary",
        header=[
            "Scenario",
            "$n$",
            "Max $|\\Delta\\log_{10}\\mathrm{Da}|$",
            "Median $|\\Delta|$",
            "Pairs $> 0.3$",
        ],
        rows=rows,
        colspec="lrrrr",
    )


def t_benchmark_resolution():
    df = pd.read_csv(TABLES_CSV / "benchmark_resolution_sensitivity.csv")
    rows = []
    for _, r in df.iterrows():
        sid = str(r["system_id"])
        rows.append([
            _display_id(sid),
            f"{int(r['daily_n_events_baseline'])}" if pd.notna(r["daily_n_events_baseline"]) else "---",
            f"{int(r['instantaneous_n_events_baseline'])}" if pd.notna(r["instantaneous_n_events_baseline"]) else "---",
            f"{r['daily_HI_median']:.3f}" if pd.notna(r["daily_HI_median"]) else "---",
            f"{r['instantaneous_HI_median']:.3f}" if pd.notna(r["instantaneous_HI_median"]) else "---",
            f"{r['dHI_inst_minus_daily']:+.3f}" if pd.notna(r["dHI_inst_minus_daily"]) else "---",
            str(r.get("preferred_data_resolution", "")),
        ])
    write_table(
        "benchmark_resolution",
        caption=(
            "Benchmark HI median by data resolution. $\\Delta\\mathrm{HI}$ is "
            "instantaneous minus daily; the preferred resolution column reflects "
            "the resolution used in the main-text envelopes."
        ),
        label="tab:benchmark_resolution",
        header=[
            "Site",
            "$n_{\\mathrm{daily}}$",
            "$n_{\\mathrm{inst}}$",
            "$\\mathrm{HI}_{\\mathrm{daily}}$",
            "$\\mathrm{HI}_{\\mathrm{inst}}$",
            "$\\Delta\\mathrm{HI}$",
            "Preferred",
        ],
        rows=rows,
        colspec="lrrrrrl",
    )


def t_hi_metric_centroids():
    df = pd.read_csv(TABLES_CSV / "hi_metric_sensitivity_centroids.csv")
    grp = df.groupby(["Q_CUTOFF_FRAC", "SPAN_MIN_DECADES"])["centroid_shift_decades"].agg(
        ["min", "max", "median", "count"]
    ).reset_index().sort_values(["Q_CUTOFF_FRAC", "SPAN_MIN_DECADES"])
    rows = []
    for _, r in grp.iterrows():
        rows.append([
            f"$10^{{{int(np.log10(r['Q_CUTOFF_FRAC']))}}}$",
            f"{r['SPAN_MIN_DECADES']:.2f}",
            f"{int(r['count'])}",
            f"{r['median']:+.3f}",
            f"{r['min']:+.3f}",
            f"{r['max']:+.3f}",
        ])
    write_table(
        "hi_metric_centroids",
        caption=(
            "Centroid shift in $\\log_{10}\\mathrm{Da}$ versus the synthetic "
            "baseline ($f_{\\mathrm{cut}} = 10^{-8}$, $\\Delta_{\\mathrm{min}} "
            "= 0.05$) under the HI metric-parameter sensitivity grid. "
            "Each row aggregates across five representative storage "
            "contrasts selected from the full 25-contrast sweep; the $n$ "
            "column is the count of aggregated contrasts per row."
        ),
        label="tab:hi_metric_centroids",
        header=[
            "$f_{\\mathrm{cut}}$",
            "$\\Delta_{\\mathrm{min}}$",
            "$n$",
            "Median shift",
            "Min",
            "Max",
        ],
        rows=rows,
        colspec="rrrrrr",
    )


def t_block_cv():
    df = pd.read_csv(TABLES_CSV / "benchmark_block_cv_summary.csv")
    rows = []
    for _, r in df.iterrows():
        rows.append([
            _display_id(r["system_id"]),
            f"{int(r['n_years'])}",
            f"{int(r['n_events_total'])}",
            f"{r['HI_median_full']:.3f}",
            f"{r['max_abs_deviation_median']:.3f}",
            f"{r['cv_of_median']:.3f}",
            f"{r['median_range']:.3f}",
        ])
    write_table(
        "block_cv",
        caption=(
            "Leave-year-out block cross-validation of benchmark HI medians. "
            "Stability of the median across folds confirms that benchmark HI "
            "estimates are not dominated by events from a single anomalous year."
        ),
        label="tab:block_cv",
        header=[
            "Site",
            "Years",
            "Events",
            "$\\mathrm{HI}_{\\mathrm{full}}$",
            "Max $|$dev.$|$",
            "CV of median",
            "Median range",
        ],
        rows=rows,
        colspec="lrrrrrr",
    )


def t_multisig():
    df = pd.read_csv(TABLES_CSV / "multisignature_cv_comparison.csv")
    keep_cols = [
        "comparison_id", "metric_id", "balanced_accuracy_mean",
        "balanced_accuracy_ci_lo", "balanced_accuracy_ci_hi",
        "roc_auc_mean", "roc_auc_ci_lo", "roc_auc_ci_hi",
    ]
    df = df[keep_cols].copy()
    rows = []
    for _, r in df.iterrows():
        rows.append([
            str(r["comparison_id"]).replace("_", r"\_"),
            str(r["metric_id"]).replace("_", r"\_"),
            f"{r['balanced_accuracy_mean']:.3f}",
            f"[{r['balanced_accuracy_ci_lo']:.3f}, {r['balanced_accuracy_ci_hi']:.3f}]",
            f"{r['roc_auc_mean']:.3f}",
            f"[{r['roc_auc_ci_lo']:.3f}, {r['roc_auc_ci_hi']:.3f}]",
        ])
    write_table(
        "multisignature_cv",
        caption=(
            "Stratified 5-fold cross-validated discrimination ($\\times$20 repeats) "
            "for HI alone, slope alone, and HI~+~slope across the synthetic "
            "ridge-core/off-ridge contrast and the field benchmark contrasts. "
            "Reported bounds are 95\\% empirical intervals (2.5th--97.5th percentiles) "
            "across the 100 repeat$\\times$fold estimates, not parametric confidence intervals."
        ),
        label="tab:multisignature_cv",
        header=[
            "Comparison",
            "Metric",
            "Bal. acc.",
            "95\\% interval",
            "ROC-AUC",
            "95\\% interval",
        ],
        rows=rows,
        colspec="llrcrc",
        fontsize=r"\footnotesize",
    )


def t_derivative_robustness():
    df = pd.read_csv(TABLES_CSV / "derivative_robustness_summary.csv")
    rows = []
    for _, r in df.iterrows():
        # Map the internal regime-ID code to the main-text display name so
        # "simple_off_ridge" reads as "simple-system reference" everywhere.
        _regime_display = {
            "ridge": "ridge",
            "floor": "low-$\\mathrm{Da}$ floor",
            "simple_off_ridge": "simple-system ref.",
            "unclassified": "unclassified",
        }
        rows.append([
            str(r["site_label"]).replace("_", r"\_"),
            f"{int(r['n_events'])}",
            f"{r['HI_median_gradient']:.3f}",
            f"{r['HI_median_savgol']:.3f}",
            f"{r['abs_shift_HI_median']:.3f}",
            _regime_display.get(str(r["regime_baseline"]), str(r["regime_baseline"]).replace("_", r"\_")),
        ])
    write_table(
        "derivative_robustness",
        caption=(
            "Derivative-method robustness check at the three primary control "
            "sites, using the main-text provenance "
            "(preferred-resolution \\textit{instantaneous} events under the "
            "\\textit{baseline} filter). Median HI is recomputed with a "
            "Savitzky--Golay filter (window 7, polynomial order 2) and "
            "compared to the baseline central-difference (gradient) HI. "
            "Absolute median shifts of 0.25--0.31 are substantial, so the "
            "Savgol variant would require rerunning the regime-consistency "
            "analysis before a classification-change conclusion can be "
            "drawn; the present table reports only the baseline regime."
        ),
        label="tab:derivative_robustness",
        header=[
            "Site",
            "Events",
            "$\\mathrm{HI}_{\\mathrm{grad.}}$",
            "$\\mathrm{HI}_{\\mathrm{savgol}}$",
            "$|\\Delta\\mathrm{HI}_{\\mathrm{median}}|$",
            "Baseline regime",
        ],
        rows=rows,
        colspec="lrrrrl",
        fontsize=r"\footnotesize",
    )


def t_outflow_exponent_summary():
    df = pd.read_csv(TABLES_CSV / "outflow_exponent_centroid_comparison.csv")
    grp = df.groupby("exponent")["shift_decades"].agg(
        ["count", "median", lambda s: s.abs().max(), lambda s: s.abs().median()]
    )
    grp.columns = ["n", "signed_median", "max_abs", "median_abs"]
    grp = grp.reset_index()
    rows = []
    for _, r in grp.iterrows():
        rows.append([
            str(r["exponent"]).replace("_", r"\_"),
            f"{int(r['n'])}",
            f"{r['signed_median']:+.3f}",
            f"{r['median_abs']:.3f}",
            f"{r['max_abs']:.3f}",
        ])
    write_table(
        "outflow_exponent_summary",
        caption=(
            "Centroid-shift summary for outflow exponents $n \\in \\{1.0, 1.5, 3.0\\}$ "
            "relative to the $n = 2.0$ baseline, aggregated over 25 storage contrasts."
        ),
        label="tab:outflow_exponent_summary",
        header=[
            "Exponent",
            "$n$",
            "Median signed shift",
            "Median $|\\mathrm{shift}|$",
            "Max $|\\mathrm{shift}|$",
        ],
        rows=rows,
        colspec="lrrrr",
    )


def t_forcing_family_summary():
    df = pd.read_csv(TABLES_CSV / "forcing_family_centroid_comparison.csv")
    grp = df.groupby("family").agg(
        n=("shift_decades", "size"),
        signed_median=("shift_decades", "median"),
        max_abs=("shift_decades", lambda s: s.abs().max()),
        median_abs=("shift_decades", lambda s: s.abs().median()),
        peak_HI_baseline_med=("peak_HI_baseline", "median"),
        peak_HI_new_med=("peak_HI_new", "median"),
    ).reset_index()
    rows = []
    for _, r in grp.iterrows():
        rows.append([
            str(r["family"]).replace("_", r"\_"),
            f"{int(r['n'])}",
            f"{r['signed_median']:+.3f}",
            f"{r['max_abs']:.3f}",
            f"{r['peak_HI_baseline_med']:.3f}",
            f"{r['peak_HI_new_med']:.3f}",
        ])
    write_table(
        "forcing_family_summary",
        caption=(
            "Forcing-family robustness summary: centroid shifts in "
            "$\\log_{10}\\mathrm{Da}$ relative to the triangular baseline, plus "
            "median peak-HI before and after the family substitution. The ridge "
            "persists under all three families."
        ),
        label="tab:forcing_family_summary",
        header=[
            "Family",
            "$n$",
            "Median signed shift",
            "Max $|\\mathrm{shift}|$",
            "$\\mathrm{HI}_{\\mathrm{peak,~base}}$",
            "$\\mathrm{HI}_{\\mathrm{peak,~new}}$",
        ],
        rows=rows,
        colspec="lrrrrr",
    )


def t_rescaling_diagnostics():
    df = pd.read_csv(TABLES_CSV / "rescaling_diagnostics.csv")
    rows = []
    for _, r in df.iterrows():
        rows.append([
            str(r["bin_label"]).replace("_", r"\_"),
            f"{int(r['n'])}",
            f"{100*r['residual_median']:.3f}\\%",
            f"{100*r['residual_q75']:.3f}\\%",
            f"{100*r['residual_q95']:.3f}\\%",
            f"{int(r['n_exceeding_5pct'])}",
            f"{int(r['n_exceeding_10pct'])}",
            f"{int(r['n_clip_total'])}",
        ])
    write_table(
        "rescaling_diagnostics",
        caption=(
            "One-step $\\alpha$-rescaling residual mismatch and clip-bound "
            "diagnostics. The residual column is "
            "$|\\mathrm{Da}_{R,\\mathrm{achieved}} - \\mathrm{Da}_{R,\\mathrm{target}}| / "
            "|\\mathrm{Da}_{R,\\mathrm{target}}|$ in percent. The clip column "
            "counts realizations that hit either the lower ($10^{-3} \\alpha_0$) "
            "or upper ($10^{3} \\alpha_0$) clipping bound. Residuals grow "
            "monotonically with storage contrast $R$ (as expected from the "
            "stronger $H_{\\mathrm{peak}}$--$\\alpha$ nonlinearity at large $R$), "
            "but no realization hits the $\\alpha_0$ clipping bound at any "
            "contrast, so the clipping prior is non-binding for the reported "
            "sweep."
        ),
        label="tab:rescaling_diagnostics",
        header=[
            "$R$ bin",
            "$n$",
            "median",
            "$q_{75}$",
            "$q_{95}$",
            "$n > 5\\%$",
            "$n > 10\\%$",
            "$n$ clipped",
        ],
        rows=rows,
        colspec="lrrrrrrr",
        fontsize=r"\footnotesize",
    )


def t_benchmark_provenance():
    df = pd.read_csv(TABLES_CSV / "benchmark_provenance.csv")
    rows = []
    for _, r in df.iterrows():
        sid = _display_id(r["system_id"])
        rows.append([
            sid,
            str(r["preferred_data_resolution"]),
            f"{int(r['n_events_baseline'])}" if pd.notna(r["n_events_baseline"]) else "---",
            f"[{r['R_lo']:.1f}, {r['R_hi']:.1f}]" if pd.notna(r["R_lo"]) else "---",
            f"{r['HI_obs_median']:.3f}" if pd.notna(r["HI_obs_median"]) else "---",
            f"[{r['HI_obs_lo']:.3f}, {r['HI_obs_hi']:.3f}]" if pd.notna(r["HI_obs_lo"]) else "---",
        ])
    write_table(
        "benchmark_provenance",
        caption=(
            "Benchmark site provenance and observed-HI envelope. The $R$ range "
            "is the literature-constrained storage-contrast bracket; HI bounds "
            "are the 10\\textsuperscript{th}--90\\textsuperscript{th} percentile "
            "of event-level HI under the preferred resolution and baseline filter."
        ),
        label="tab:benchmark_provenance",
        header=[
            "Site",
            "Preferred",
            "Events",
            "$R$ range",
            "$\\mathrm{HI}_{\\mathrm{obs}}$ (median)",
            "$q_{10}$--$q_{90}$",
        ],
        rows=rows,
        colspec="llrcrc",
        fontsize=r"\footnotesize",
    )


GENERATORS = [
    ("centroid_ridge_main", t_centroid_ridge),
    ("dt_convergence", t_dt_convergence),
    ("forcing_stress_summary", t_forcing_stress_summary),
    ("benchmark_resolution", t_benchmark_resolution),
    ("hi_metric_centroids", t_hi_metric_centroids),
    ("block_cv", t_block_cv),
    ("multisignature_cv", t_multisig),
    ("derivative_robustness", t_derivative_robustness),
    ("outflow_exponent_summary", t_outflow_exponent_summary),
    ("forcing_family_summary", t_forcing_family_summary),
    ("benchmark_provenance", t_benchmark_provenance),
    ("rescaling_diagnostics", t_rescaling_diagnostics),
]


def main():
    print(f"Writing tables to {TABLES_TEX.relative_to(PKG)}/")
    for name, fn in GENERATORS:
        try:
            fn()
        except Exception as e:
            print(f"  ! failed {name}: {e}")
    print("Done.")


if __name__ == "__main__":
    main()
