#!/usr/bin/env python3
"""Build the SI S15 per-site envelope comparison table directly from
benchmark_regime_consistency.csv so it reflects the actual
preferred-regime-by-rule output rather than a re-implemented decision logic.

also reports (i) the
observed event q10-q90 alongside the classifier's bootstrap-median CI,
(ii) the low-Da floor envelope bounds, and (iii) per-envelope overlap
fractions, so every site assignment is fully auditable from one row of
the table.
"""
from pathlib import Path
import pandas as pd

PKG = Path(__file__).resolve().parent.parent
TABLES = PKG / "tables"
OUT_TEX = PKG / "manuscript" / "tables_tex"
OUT_TEX.mkdir(parents=True, exist_ok=True)


regime = pd.read_csv(TABLES / "benchmark_regime_consistency.csv")
envelopes = pd.read_csv(TABLES / "benchmark_regime_envelopes.csv")
hi_env = pd.read_csv(TABLES / "benchmark_hi_envelope.csv")

SITES = [
    ("USGS-07014500", "Meramec"),
    ("USGS-07067500", "Big Spring"),
    ("USGS-02322500", "Ichetucknee"),
    ("USGS-08155500", "Barton"),
    ("USGS-08169000", "Comal"),
    ("USGS-08171000", "Blanco"),
    ("11148900",      "Arroyo Seco"),
    ("1013500",       "Fish River"),
]

REGIME_DISPLAY = {
    "ridge": "ridge",
    "floor": "low-$\\mathrm{Da}$ floor",
    "simple_off_ridge": "low-$R$ off-shoulder ref.",
    "unclassified": "unclassified",
}


def _ov_for(sub, regime_id):
    r = sub[sub["regime_id"] == regime_id]
    if r.empty:
        return None
    return float(r["overlap_fraction_obs"].iloc[0])


def _env_pair(sub_env, regime_id):
    r = sub_env[sub_env["regime_id"] == regime_id]
    if r.empty:
        return None
    return float(r["HI_median"].iloc[0]), float(r["HI_lo"].iloc[0]), float(r["HI_hi"].iloc[0])


rows = []
for sid, label in SITES:
    sub_env = envelopes[envelopes["system_id"] == sid]
    sub_reg = regime[regime["system_id"] == sid]
    hi_row = hi_env[hi_env["system_id"].astype(str) == sid]
    if hi_row.empty:
        continue
    obs_med = float(hi_row["HI_obs_median"].iloc[0])
    obs_ci_lo = float(hi_row["HI_obs_median_ci_lo"].iloc[0])
    obs_ci_hi = float(hi_row["HI_obs_median_ci_hi"].iloc[0])
    evt_q10 = float(hi_row["HI_obs_event_q10"].iloc[0])
    evt_q90 = float(hi_row["HI_obs_event_q90"].iloc[0])
    n_evt = int(hi_row["n_events_baseline_preferred"].iloc[0])

    rg = _env_pair(sub_env, "ridge")
    ss = _env_pair(sub_env, "simple_off_ridge")
    fl = _env_pair(sub_env, "floor")

    ov_rg = _ov_for(sub_reg, "ridge")
    ov_ss = _ov_for(sub_reg, "simple_off_ridge")
    ov_fl = _ov_for(sub_reg, "floor")

    pref = str(sub_reg["preferred_regime_by_rule"].iloc[0]) if not sub_reg.empty else "—"
    rule = str(sub_reg["preference_rule_applied"].iloc[0]) if not sub_reg.empty else "—"
    rows.append({
        "site": label,
        "system_id": sid,
        "n_events": n_evt,
        "obs_median": obs_med,
        "obs_ci_lo": obs_ci_lo,
        "obs_ci_hi": obs_ci_hi,
        "event_q10": evt_q10,
        "event_q90": evt_q90,
        "ridge_med": rg[0] if rg else None,
        "ridge_lo": rg[1] if rg else None,
        "ridge_hi": rg[2] if rg else None,
        "ridge_overlap": ov_rg if ov_rg is not None else 0.0,
        "floor_med": fl[0] if fl else None,
        "floor_lo": fl[1] if fl else None,
        "floor_hi": fl[2] if fl else None,
        "floor_overlap": ov_fl if ov_fl is not None else 0.0,
        "ss_med": ss[0] if ss else None,
        "ss_lo": ss[1] if ss else None,
        "ss_hi": ss[2] if ss else None,
        "ss_overlap": ov_ss if ov_ss is not None else 0.0,
        "preferred": pref,
        "rule": rule,
    })

df = pd.DataFrame(rows)
df.to_csv(TABLES / "s15_envelope_comparison.csv", index=False)


def _fmt_id(sid):
    s = str(sid).replace("USGS-", "")
    if s.isdigit():
        s = s.zfill(8)
    return s


# Render LaTeX table (now with all three envelopes, observed interval, and overlap fractions)
body_rows = []
for _, r in df.iterrows():
    disp = REGIME_DISPLAY.get(r["preferred"], r["preferred"]).replace("_", r"\_")
    body_rows.append(
        " & ".join([
            f"{r['site']} ({_fmt_id(r['system_id'])})",
            f"{int(r['n_events'])}",
            f"{r['obs_median']:.3f}",
            f"[{r['obs_ci_lo']:.3f}, {r['obs_ci_hi']:.3f}]",
            f"[{r['event_q10']:.3f}, {r['event_q90']:.3f}]",
            f"[{r['ridge_lo']:.3f}, {r['ridge_hi']:.3f}]",
            f"{r['ridge_overlap']:.3f}",
            f"[{r['floor_lo']:.3f}, {r['floor_hi']:.3f}]",
            f"{r['floor_overlap']:.3f}",
            f"[{r['ss_lo']:.3f}, {r['ss_hi']:.3f}]",
            f"{r['ss_overlap']:.3f}",
            disp,
        ]) + r" \\"
    )

tex = (
    "% Auto-generated by regen_s15_envelope_table.py — do not edit.\n"
    "\\begin{sidewaystable}[ht]\n"
    "\\caption{Baseline-cutoff ($f_{\\mathrm{cut}} = 10^{-8}$) per-site "
    "envelope comparison and preferred regime, built from "
    "\\texttt{tables/benchmark\\_regime\\_consistency.csv}. All values are "
    "directly auditable: observed interval is the bootstrap 10--90 CI of "
    "the site median HI used by the classifier; the event $[q_{10}, q_{90}]$ "
    "column is the raw event-level spread reported for context. Overlap "
    "fractions are computed on the observed bootstrap-CI interval against "
    "each envelope's bounds (ridge and floor: $[q_{10}, q_{90}]$ of "
    "the pooled sample; low-$R$ off-shoulder reference: $[\\min, \\max]$ "
    "of the pooled sample --- see main-text Methods Section~3.5 "
    "for the explicit asymmetry rationale). The \\textit{preferred regime} "
    "column is the output of the production decision rule "
    "(overlap-fraction-first; median-distance tie-breaker when one envelope "
    "fully contains the observed interval and $\\geq$2 envelopes cover at "
    "least 50\\%; \\textit{unclassified} when no envelope achieves "
    "$\\geq$5\\% overlap). A matched-cutoff ($f_{\\mathrm{cut}} = 10^{-9}$) "
    "regime rerun is deferred as a follow-on analysis "
    "(Section~\\ref{sec:S15}); the matched-cutoff ridge and simple-system "
    "envelope medians are reported in narrative form in "
    "Section~\\ref{sec:S15}.}\n"
    "\\label{tab:s15_envelope_comparison}\n"
    "\\centering\n"
    "\\scriptsize\n"
    "\\begin{tabular}{lrrccccccccl}\n"
    "\\toprule\n"
    "Site & $n_{\\mathrm{evt}}$ & $\\mathrm{HI}_{\\mathrm{obs,med}}$ & "
    "Obs. med.\\ CI & Event $[q_{10},q_{90}]$ & "
    "Ridge $[q_{10},q_{90}]$ & Ridge ov. & "
    "Floor $[q_{10},q_{90}]$ & Floor ov. & "
    "SS $[\\min,\\max]$ & SS ov. & Preferred regime \\\\\n"
    "\\midrule\n"
    + "\n".join(body_rows) +
    "\n\\bottomrule\n\\end{tabular}\n\\end{sidewaystable}\n"
)
(OUT_TEX / "s15_envelope_comparison.tex").write_text(tex)

print(f"Wrote tables/s15_envelope_comparison.csv and manuscript/tables_tex/s15_envelope_comparison.tex")
print(df[['site','n_events','obs_median','ridge_overlap','ss_overlap','preferred']].to_string(index=False))
